ALTER TABLE empresa ADD COLUMN data_alteracao TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE endereco ADD COLUMN data_alteracao TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE endereco ADD COLUMN data_criacao TIMESTAMP NOT NULL DEFAULT NOW();