drop table horario_funcionamento;

create table horario_funcionamento (
  id uuid not null,
  id_empresa uuid not null,
  segunda_ini time without time zone,
  segunda_fim time without time zone,
  segunda_ini_2 time without time zone,
  segunda_fim_2 time without time zone,
  terca_ini time without time zone,
  terca_fim time without time zone,
  terca_ini_2 time without time zone,
  terca_fim_2 time without time zone,
  quarta_ini time without time zone,
  quarta_fim time without time zone,
  quarta_ini_2 time without time zone,
  quarta_fim_2 time without time zone,
  quinta_ini time without time zone,
  quinta_fim time without time zone,
  quinta_ini_2 time without time zone,
  quinta_fim_2 time without time zone,
  sexta_ini time without time zone,
  sexta_fim time without time zone,
  sexta_ini_2 time without time zone,
  sexta_fim_2 time without time zone,
  sabado_ini time without time zone,
  sabado_fim time without time zone,
  sabado_ini_2 time without time zone,
  sabado_fim_2 time without time zone,
  domingo_ini time without time zone,
  domingo_fim time without time zone,
  domingo_ini_2 time without time zone,
  domingo_fim_2 time without time zone,
  data_alteracao TIMESTAMP NOT NULL DEFAULT NOW(),
  data_criacao TIMESTAMP NOT NULL DEFAULT NOW(),
  primary key (id),
  constraint fk_horario_funcionamento_empresa foreign key (id_empresa) references empresa
);